CREATE TABLE IF NOT EXISTS `users` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `name` VARCHAR(150) NOT NULL,
  `email` VARCHAR(150) DEFAULT NULL UNIQUE,
  `mobile` VARCHAR(15) NOT NULL UNIQUE,
  `password_hash` VARCHAR(255) NOT NULL,
  `pin_hash` VARCHAR(255) DEFAULT NULL,
  `role_id` INT UNSIGNED NOT NULL,
  `branch_id` INT UNSIGNED DEFAULT NULL,
  `area_id` INT UNSIGNED DEFAULT NULL,
  `agent_id` INT UNSIGNED DEFAULT NULL,
  `policy_id` INT UNSIGNED DEFAULT NULL,
  `photo_path` VARCHAR(500) DEFAULT NULL,
  `status` ENUM('Active','Inactive','Suspended') DEFAULT 'Active',
  `last_login_at` DATETIME DEFAULT NULL,
  `auth_token` VARCHAR(500) DEFAULT NULL,
  `token_expires_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  FOREIGN KEY (`role_id`) REFERENCES `roles`(`id`),
  INDEX `idx_users_mobile` (`mobile`),
  INDEX `idx_users_email` (`email`),
  INDEX `idx_users_role` (`role_id`),
  INDEX `idx_users_branch` (`branch_id`),
  INDEX `idx_users_status` (`status`)
) ENGINE=InnoDB;
