CREATE TABLE IF NOT EXISTS `agents` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `code` VARCHAR(20) NOT NULL UNIQUE,
  `name` VARCHAR(150) NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `email` VARCHAR(150) DEFAULT NULL,
  `user_id` INT UNSIGNED DEFAULT NULL,
  `branch_id` INT UNSIGNED NOT NULL,
  `area_id` INT UNSIGNED NOT NULL,
  `policy_id` INT UNSIGNED DEFAULT NULL,
  `photo_path` VARCHAR(500) DEFAULT NULL,
  `father_name` VARCHAR(150) DEFAULT NULL,
  `dob` DATE DEFAULT NULL,
  `address` TEXT DEFAULT NULL,
  `aadhaar_no` VARCHAR(20) DEFAULT NULL,
  `pan_no` VARCHAR(15) DEFAULT NULL,
  `bank_name` VARCHAR(100) DEFAULT NULL,
  `bank_account_no` VARCHAR(30) DEFAULT NULL,
  `bank_ifsc` VARCHAR(15) DEFAULT NULL,
  `joining_date` DATE DEFAULT NULL,
  `status` ENUM('Active','Inactive','Suspended') DEFAULT 'Active',
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`),
  FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`),
  FOREIGN KEY (`policy_id`) REFERENCES `policies`(`id`),
  INDEX `idx_agents_branch` (`branch_id`),
  INDEX `idx_agents_area` (`area_id`),
  INDEX `idx_agents_mobile` (`mobile`),
  INDEX `idx_agents_code` (`code`),
  INDEX `idx_agents_status` (`status`)
) ENGINE=InnoDB;
