CREATE TABLE IF NOT EXISTS `customers` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `customer_code` VARCHAR(25) NOT NULL UNIQUE,
  `full_name` VARCHAR(200) NOT NULL,
  `mobile` VARCHAR(15) NOT NULL,
  `alternate_mobile` VARCHAR(15) DEFAULT NULL,
  `dob` DATE DEFAULT NULL,
  `gender` ENUM('Male','Female','Other') DEFAULT 'Male',
  `father_or_husband_name` VARCHAR(200) DEFAULT NULL,
  `occupation` VARCHAR(150) DEFAULT NULL,
  `monthly_income` DECIMAL(18,2) DEFAULT 0.00,
  `photo_path` VARCHAR(500) DEFAULT NULL,
  `branch_id` INT UNSIGNED NOT NULL,
  `area_id` INT UNSIGNED NOT NULL,
  `agent_id` INT UNSIGNED NOT NULL,
  `status` ENUM('Active','Blocked','Deactive') DEFAULT 'Active',
  `created_by` INT UNSIGNED DEFAULT NULL,
  `updated_by` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  INDEX `idx_customers_mobile` (`mobile`),
  INDEX `idx_customers_code` (`customer_code`),
  INDEX `idx_customers_branch` (`branch_id`),
  INDEX `idx_customers_area` (`area_id`),
  INDEX `idx_customers_agent` (`agent_id`),
  INDEX `idx_customers_status` (`status`),
  INDEX `idx_customers_created` (`created_at`),
  FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`),
  FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`),
  FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`)
) ENGINE=InnoDB;
