CREATE TABLE IF NOT EXISTS `loan_accounts` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `loan_account_no` VARCHAR(25) NOT NULL UNIQUE,
  `customer_id` INT UNSIGNED NOT NULL,
  `loan_plan_id` INT UNSIGNED NOT NULL,
  `plan_name` VARCHAR(200) DEFAULT NULL,
  `branch_id` INT UNSIGNED NOT NULL,
  `area_id` INT UNSIGNED NOT NULL,
  `agent_id` INT UNSIGNED NOT NULL,
  `principal_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `interest_rate` DECIMAL(6,2) NOT NULL DEFAULT 0.00,
  `interest_type` ENUM('Flat','Reducing') DEFAULT 'Flat',
  `interest_amount` DECIMAL(18,2) DEFAULT 0.00,
  `processing_fee` DECIMAL(18,2) DEFAULT 0.00,
  `penalty_amount` DECIMAL(18,2) DEFAULT 0.00,
  `total_payable` DECIMAL(18,2) DEFAULT 0.00,
  `emi_amount` DECIMAL(18,2) DEFAULT 0.00,
  `duration_days` INT DEFAULT 0,
  `duration_months` INT DEFAULT 0,
  `collection_frequency` ENUM('Daily','Weekly','Monthly') DEFAULT 'Daily',
  `start_date` DATE DEFAULT NULL,
  `end_date` DATE DEFAULT NULL,
  `total_paid` DECIMAL(18,2) DEFAULT 0.00,
  `outstanding_amount` DECIMAL(18,2) DEFAULT 0.00,
  `account_status` ENUM('Processing','Approved','Active','Defaulter','NPA','Closed','Rejected') DEFAULT 'Processing',
  `approved_by` INT UNSIGNED DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `closed_at` DATETIME DEFAULT NULL,
  `closed_by` INT UNSIGNED DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`),
  FOREIGN KEY (`loan_plan_id`) REFERENCES `loan_plans`(`id`),
  FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`),
  FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`),
  FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`),
  INDEX `idx_loan_acc_no` (`loan_account_no`),
  INDEX `idx_loan_acc_customer` (`customer_id`),
  INDEX `idx_loan_acc_branch` (`branch_id`),
  INDEX `idx_loan_acc_area` (`area_id`),
  INDEX `idx_loan_acc_agent` (`agent_id`),
  INDEX `idx_loan_acc_status` (`account_status`),
  INDEX `idx_loan_acc_created` (`created_at`)
) ENGINE=InnoDB;
