CREATE TABLE IF NOT EXISTS `loan_collections` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `receipt_no` VARCHAR(25) NOT NULL UNIQUE,
  `loan_account_id` INT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `installment_id` INT UNSIGNED DEFAULT NULL,
  `branch_id` INT UNSIGNED NOT NULL,
  `area_id` INT UNSIGNED NOT NULL,
  `agent_id` INT UNSIGNED NOT NULL,
  `collection_date` DATE NOT NULL,
  `collected_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `principal_amount` DECIMAL(18,2) DEFAULT 0.00,
  `interest_amount` DECIMAL(18,2) DEFAULT 0.00,
  `penalty_amount` DECIMAL(18,2) DEFAULT 0.00,
  `payment_mode` ENUM('Cash','UPI','Bank Transfer','Cheque','Online') DEFAULT 'Cash',
  `remarks` TEXT DEFAULT NULL,
  `collected_by` INT UNSIGNED NOT NULL,
  `is_reversal` TINYINT(1) DEFAULT 0,
  `reversal_of` INT UNSIGNED DEFAULT NULL,
  `is_advance` TINYINT(1) DEFAULT 0,
  `installment_allocations` JSON DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`loan_account_id`) REFERENCES `loan_accounts`(`id`),
  FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`),
  FOREIGN KEY (`installment_id`) REFERENCES `loan_installments`(`id`) ON DELETE SET NULL,
  INDEX `idx_loan_coll_receipt` (`receipt_no`),
  INDEX `idx_loan_coll_account` (`loan_account_id`),
  INDEX `idx_loan_coll_customer` (`customer_id`),
  INDEX `idx_loan_coll_branch` (`branch_id`),
  INDEX `idx_loan_coll_area` (`area_id`),
  INDEX `idx_loan_coll_agent` (`agent_id`),
  INDEX `idx_loan_coll_date` (`collection_date`),
  INDEX `idx_loan_coll_created` (`created_at`)
) ENGINE=InnoDB;
