CREATE TABLE IF NOT EXISTS `saving_accounts` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `saving_account_no` VARCHAR(25) NOT NULL UNIQUE,
  `customer_id` INT UNSIGNED NOT NULL,
  `saving_plan_id` INT UNSIGNED NOT NULL,
  `plan_name` VARCHAR(200) DEFAULT NULL,
  `branch_id` INT UNSIGNED NOT NULL,
  `area_id` INT UNSIGNED NOT NULL,
  `agent_id` INT UNSIGNED NOT NULL,
  `deposit_amount` DECIMAL(18,2) DEFAULT 0.00,
  `interest_rate` DECIMAL(6,2) DEFAULT 0.00,
  `duration_months` INT DEFAULT 12,
  `maturity_amount` DECIMAL(18,2) DEFAULT 0.00,
  `collection_frequency` ENUM('Daily','Weekly','Monthly') DEFAULT 'Daily',
  `total_deposited` DECIMAL(18,2) DEFAULT 0.00,
  `start_date` DATE DEFAULT NULL,
  `maturity_date` DATE DEFAULT NULL,
  `account_status` ENUM('Processing','Approved','Active','Matured','Closed','Rejected') DEFAULT 'Processing',
  `approved_by` INT UNSIGNED DEFAULT NULL,
  `approved_at` DATETIME DEFAULT NULL,
  `matured_at` DATETIME DEFAULT NULL,
  `closed_at` DATETIME DEFAULT NULL,
  `closed_by` INT UNSIGNED DEFAULT NULL,
  `created_by` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `deleted_at` DATETIME DEFAULT NULL,
  FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`),
  FOREIGN KEY (`saving_plan_id`) REFERENCES `saving_plans`(`id`),
  FOREIGN KEY (`branch_id`) REFERENCES `branches`(`id`),
  FOREIGN KEY (`area_id`) REFERENCES `areas`(`id`),
  FOREIGN KEY (`agent_id`) REFERENCES `agents`(`id`),
  INDEX `idx_saving_acc_no` (`saving_account_no`),
  INDEX `idx_saving_acc_customer` (`customer_id`),
  INDEX `idx_saving_acc_branch` (`branch_id`),
  INDEX `idx_saving_acc_area` (`area_id`),
  INDEX `idx_saving_acc_agent` (`agent_id`),
  INDEX `idx_saving_acc_status` (`account_status`),
  INDEX `idx_saving_acc_maturity` (`maturity_date`),
  INDEX `idx_saving_acc_created` (`created_at`)
) ENGINE=InnoDB;
