CREATE TABLE IF NOT EXISTS `saving_deposits` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `receipt_no` VARCHAR(25) NOT NULL UNIQUE,
  `saving_account_id` INT UNSIGNED NOT NULL,
  `customer_id` INT UNSIGNED NOT NULL,
  `branch_id` INT UNSIGNED NOT NULL,
  `area_id` INT UNSIGNED NOT NULL,
  `agent_id` INT UNSIGNED NOT NULL,
  `deposit_date` DATE NOT NULL,
  `deposit_amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `payment_mode` ENUM('Cash','UPI','Bank Transfer','Cheque','Online') DEFAULT 'Cash',
  `remarks` TEXT DEFAULT NULL,
  `collected_by` INT UNSIGNED NOT NULL,
  `is_reversal` TINYINT(1) DEFAULT 0,
  `reversal_of` INT UNSIGNED DEFAULT NULL,
  `is_advance` TINYINT(1) DEFAULT 0,
  `installment_allocations` JSON DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`saving_account_id`) REFERENCES `saving_accounts`(`id`),
  FOREIGN KEY (`customer_id`) REFERENCES `customers`(`id`),
  INDEX `idx_saving_dep_receipt` (`receipt_no`),
  INDEX `idx_saving_dep_account` (`saving_account_id`),
  INDEX `idx_saving_dep_customer` (`customer_id`),
  INDEX `idx_saving_dep_branch` (`branch_id`),
  INDEX `idx_saving_dep_area` (`area_id`),
  INDEX `idx_saving_dep_agent` (`agent_id`),
  INDEX `idx_saving_dep_date` (`deposit_date`),
  INDEX `idx_saving_dep_created` (`created_at`)
) ENGINE=InnoDB;
