CREATE TABLE IF NOT EXISTS `fund_saving_history` (
  `id` INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  `uuid` CHAR(36) NOT NULL UNIQUE,
  `transaction_no` VARCHAR(25) NOT NULL,
  `fund_source_id` INT UNSIGNED DEFAULT NULL,
  `entry_type` ENUM('credit','debit') NOT NULL,
  `category` VARCHAR(50) NOT NULL,
  `amount` DECIMAL(18,2) NOT NULL DEFAULT 0.00,
  `balance_before` DECIMAL(18,2) DEFAULT NULL,
  `balance_after` DECIMAL(18,2) DEFAULT NULL,
  `reference_no` VARCHAR(50) DEFAULT NULL,
  `description` TEXT DEFAULT NULL,
  `entry_date` DATE NOT NULL,
  `entered_by` INT UNSIGNED DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (`fund_source_id`) REFERENCES `fund_sources`(`id`),
  INDEX `idx_fsh_txn` (`transaction_no`),
  INDEX `idx_fsh_date` (`entry_date`),
  INDEX `idx_fsh_category` (`category`)
) ENGINE=InnoDB;
